#
# pacman.conf for the ISO build environment.
#

[options]
Architecture = auto
CheckSpace
Color
HoldPkg = pacman glibc
LocalFileSigLevel = Optional
ParallelDownloads = 5
SigLevel = Required DatabaseOptional

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

